
name: GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
  push:
    branches:
      - main
